blank_issues_enabled: false
contact_links:
  - name: â“ Question / Support
    url: https://github.com/interactive-instruments/ldproxy/discussions/new?category=tools
    about: Get help on any issues with xtratiler 
  - name: ğŸ“š View Documentation
    url: https://docs.ldproxy.net/tools/xtratiler/
    about: Official xtratiler documentation    
